export const PROMPT_INPUT_LINE_HEIGHT = 24;
export const PROMPT_INPUT_VERTICAL_PADDING = 12;
export const PROMPT_INPUT_MAX_VISIBLE_LINES = 5;
export const PROMPT_INPUT_MAX_HEIGHT =
  PROMPT_INPUT_LINE_HEIGHT * PROMPT_INPUT_MAX_VISIBLE_LINES
    + PROMPT_INPUT_VERTICAL_PADDING * 2;
